s= set()
print(type(s))

n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))
n = int(input("Enter number:"))
s.add(int(n))

print(s)